---
- name: "configuring the local repo on all machines"
  hosts: all
  tasks:

    - name: "Deploy the key in all machines"
      ansible.builtin.rpm_key:
        url: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release
        state: present


    - name: " Configurer repo 1"
      ansible.builtin.yum_repository:
        file: EX_294
        name: EX_294
        description: "EX294 base software"
        baseurl: http://content.example.com/rhel9.0/x86_64/dvd/BaseOS
        enabled: yes
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release
        state: present


    - name: "Configure repo2 "
      ansible.builtin.yum_repository:
        file: EX294_STREM
        name: EX294_STREM
        description: "EX294 Appstream software"
        baseurl: http://content.example.com/rhel9.0/x86_64/dvd/AppStream
        enabled: yes
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release
        state: present

