---
# handlers file for node-exporter
- name: reload_daemon_and_restart_node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted

