---
- name: "Create a yum repository on managed nodes"
  hosts: all


  tasks:

    - name: "Deploy the GPG key"
      ansible.builtin.rpm_key:
          key: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release
          state: present


    - name: "Create the repository EX294_BASE"
      ansible.builtin.yum_repository:
          file: EX294_BASE
          name: EX294_BASE
          description: "EX294 base software"
          baseurl: http://content.example.com/rhel9.0/x86_64/dvd/BaseOS
          gpgcheck: yes
          gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release

    - name: "Create the repo EX294_STREM"
      ansible.builtin.yum_repository:
        file: "EX294_STREM"
        name: "EX294_STREM"
        description: "EX294 base software"
        enabled: yes
        baseurl: http://content.example.com/rhel9.0/x86_64/dvd/AppStream
        gpgcheck: yes
        gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEYredhat-release
        state: present
